import type { EmojiCard } from "./types";

// Bollywood Emoji puzzles — mainstream + famous pan-India. System-font emoji only.
// Expandable: just add rows. (Starter set; can grow to 150-250.)
export const EMOJI_DECK: EmojiCard[] = [
  { id: "be_001", answer: "3 Idiots", emoji: "3️⃣🤪", difficulty: "easy" },
  { id: "be_002", answer: "Dangal", emoji: "🤼🥇", difficulty: "easy" },
  {
    id: "be_003",
    answer: "Dilwale Dulhania Le Jayenge",
    emoji: "💖🚂🌾",
    difficulty: "medium",
  },
  { id: "be_004", answer: "Bajrangi Bhaijaan", emoji: "🐒🙏👧", difficulty: "medium" },
  { id: "be_005", answer: "PK", emoji: "👽📻", difficulty: "easy" },
  { id: "be_006", answer: "Andhadhun", emoji: "🎹🙈", difficulty: "hard" },
  { id: "be_007", answer: "Lagaan", emoji: "🏏☔💰", difficulty: "medium" },
  { id: "be_008", answer: "Taare Zameen Par", emoji: "⭐🌍🎨", difficulty: "medium" },
  { id: "be_009", answer: "Stree", emoji: "👻👗", difficulty: "medium" },
  {
    id: "be_010",
    answer: "Uri: The Surgical Strike",
    emoji: "🇮🇳🎖️💥",
    difficulty: "medium",
  },
  { id: "be_011", answer: "Gully Boy", emoji: "🎤🏙️", difficulty: "hard" },
  { id: "be_012", answer: "Kahaani", emoji: "🤰🔍", difficulty: "hard" },
  { id: "be_013", answer: "Singham", emoji: "🦁👮", difficulty: "easy" },
  { id: "be_014", answer: "Tanu Weds Manu", emoji: "👰🤵", difficulty: "medium" },
  { id: "be_015", answer: "Bhaag Milkha Bhaag", emoji: "🏃💨🥇", difficulty: "medium" },
  { id: "be_016", answer: "Sholay", emoji: "🔥🌶️🔫", difficulty: "easy" },
  { id: "be_017", answer: "Don", emoji: "🕴️🚬💼", difficulty: "medium" },
  { id: "be_018", answer: "Krrish", emoji: "🦸🇮🇳", difficulty: "easy" },
  { id: "be_019", answer: "Padmaavat", emoji: "👑🔥🪔", difficulty: "medium" },
  { id: "be_020", answer: "Barfi", emoji: "🍬🙉🙊", difficulty: "hard" },
  { id: "be_021", answer: "Chennai Express", emoji: "🚆🌴💃", difficulty: "medium" },
  {
    id: "be_022",
    answer: "Zindagi Na Milegi Dobara",
    emoji: "✈️🤿🐂",
    difficulty: "hard",
  },
  { id: "be_023", answer: "Queen", emoji: "👸✈️🍷", difficulty: "medium" },
  { id: "be_024", answer: "Munna Bhai MBBS", emoji: "🩺🤗😎", difficulty: "medium" },
  { id: "be_025", answer: "Drishyam", emoji: "📺👨‍👩‍👧🚔", difficulty: "hard" },
  { id: "be_026", answer: "Ra.One", emoji: "🎮🤖1️⃣", difficulty: "medium" },
  { id: "be_027", answer: "Golmaal", emoji: "🤡🙉😂", difficulty: "medium" },
  { id: "be_028", answer: "Dhoom", emoji: "🏍️💨💰", difficulty: "easy" },
  { id: "be_029", answer: "Kabir Singh", emoji: "💔🍺🩺", difficulty: "medium" },
  { id: "be_030", answer: "Bahubali", emoji: "💪👑⚔️", difficulty: "easy" },
  { id: "be_031", answer: "RRR", emoji: "🔥💧🐅", difficulty: "easy" },
  { id: "be_032", answer: "Pushpa", emoji: "🌳🚚🧔", difficulty: "medium" },
  { id: "be_033", answer: "Jawan", emoji: "🧑‍🦲🔫🚇", difficulty: "medium" },
  { id: "be_034", answer: "Pathaan", emoji: "🕵️🇮🇳🔥", difficulty: "medium" },
  { id: "be_035", answer: "Animal", emoji: "🪓🩸🐺", difficulty: "medium" },
  { id: "be_036", answer: "Hera Pheri", emoji: "📞💰😵", difficulty: "medium" },
  { id: "be_037", answer: "Jab We Met", emoji: "🚆😄❤️", difficulty: "medium" },
  { id: "be_038", answer: "Om Shanti Om", emoji: "🕉️🎬🔥", difficulty: "medium" },
  { id: "be_039", answer: "Bhool Bhulaiyaa", emoji: "👻🏰💃", difficulty: "medium" },
  { id: "be_040", answer: "Chhichhore", emoji: "🎓🏥🏗️", difficulty: "hard" },
  { id: "be_041", answer: "Kal Ho Naa Ho", emoji: "❤️🏥🌅", difficulty: "medium" },
  { id: "be_042", answer: "Swades", emoji: "🚀🇮🇳💡", difficulty: "hard" },
  { id: "be_043", answer: "My Name Is Khan", emoji: "🧔🏷️🌍", difficulty: "medium" },
  { id: "be_044", answer: "Rockstar", emoji: "🎸💔🤘", difficulty: "medium" },
  { id: "be_045", answer: "Highway", emoji: "🛣️🚚🏔️", difficulty: "hard" },
  { id: "be_046", answer: "Tumbbad", emoji: "🌧️🏚️🪙", difficulty: "hard" },
  { id: "be_047", answer: "Article 15", emoji: "📜1️⃣5️⃣👮", difficulty: "hard" },
  { id: "be_048", answer: "Welcome", emoji: "👋🔫😂", difficulty: "medium" },
  { id: "be_049", answer: "Race", emoji: "🏎️🔫🕶️", difficulty: "easy" },
  { id: "be_050", answer: "Ghajini", emoji: "🧠📸💪", difficulty: "hard" },
];
